Update readme and requirements
WatChMaL/WatChMaL pull request #46
Opened 2022-02-01 18:47 UTC by nickwp

2022-02-08 11:32 UTC, xligit approved these changes

2022-02-09 01:37 UTC, pdeperio requested changes
what's the `Development` section for?

2022-02-09 01:51 UTC, nickwp commented
> what's the `Development` section for?

The rest of the readme is just about using / configuring / running the code, whereas the "Development" section is intended to describe the code structure itself a bit more. I couldn't think of a better title but it's basically info for people working on the code itself rather than just using it.
The structure of the code is very similar to (but not exactly the same as) the structure of the config, so might seem like it's repeating. In future I expect there will be more to add here, for example after moving the shared functions used for analysis (plotting) into this repo, and more details when we've merged the regression and segmentation branches. Also anything that comes up as more people start working on the code and ask about.

2022-02-09 01:53 UTC, pdeperio approved these changes

2022-02-09 01:53 UTC, merged