Changes from Sid's WatChMaL version that didn't already get merged
WatChMaL/WatChMaL pull request #50
Opened 2022-04-26 06:37 UTC by nickwp

This is the version that the latest results were produced with.

Includes:
- double cover "padding" implementation
- ability to configure scheduler
- cleaned and commented engine and dataset code

2022-05-04 23:53 UTC, pdeperio requested changes
Looks good. Should the PDF documentation go in a docs folder or not in repo at al?

2022-05-05 00:04 UTC, nickwp commented
Yeah, I was wondering about that myself. I'm not sure we need it in the repo, but think I'll move to a docs folder for now.

2022-05-05 00:24 UTC, nickwp commented
I moved to a docs directory within the directory they were already placed. I think once we have more proper documentation we can create a dedicated docs folder at the top level, or move out of the repo entirely and onto the wiki or somewhere instead, but for now that didn't feel necessary. Unless you think it's more useful elsewhere?

2022-05-05 01:02 UTC, pdeperio approved these changes

2022-05-05 01:02 UTC, merged