Resnet18 Charge and Time
WatChMaL/WatChMaL pull request #65
Opened 2023-04-25 11:04 UTC by adelorenzis

2023-05-01 08:33 UTC, pdeperio commented
Thanks @adelorenzis @mpcasado! 

Please take a look at e.g. [How to Write a Pull Request](https://www.pullrequest.com/blog/writing-a-great-pull-request-description) or [The Anatomy of a PR](https://www.pullrequest.com/blog/writing-a-great-pull-request-description) to get an idea of how to write a description above, including results of testing.

I noticed you also have several `_old` files, which we don't want to store in the repository since I guess we'll never use them. Please just modify the corresponding file directly and commit; that's what this version control is for!

You'll also notice on the PR webpage several "Conflicting files". Please review these carefully to ensure you're putting in the right changes.

2023-06-22 12:37 UTC, adelorenzis commented
Hello @pdeperio @mpcasado! 
Sorry for the delay in response.
Thanks for your comments and suggestions.
I did a new pull request, I added a description, I removed the old files and I reviewed the "conflicting files".
Please, let me know if anything else is needed.

2023-06-28 07:57 UTC, pdeperio commented
@adelorenzis Thank you! Can you please resolve the conflicts below?

2023-06-28 07:59 UTC, nickwp requested changes

2023-07-06 13:28 UTC, adelorenzis commented on watchmal/dataset/cnn_mpmt/cnn_mpmt_dataset.py
> +            rand_choices = [bool(random.getrandbits(1)) for i in range(len(self.transforms))]
@nickwp I proposed a new solution and I updated the code with your suggestions. Thanks! Please let me know if it's ok now.

2023-09-05 08:08 UTC, nickwp commented
Closing this as it's replaced by #67

2023-09-05 08:08 UTC, closed without merging